name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  liquidity-venues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Run liquidity venue tests
        run: pnpm test:liquidity-venues
        env:
          RPC_URL_1: ${{ secrets.RPC_URL_1 }}
          RPC_URL_99: ${{ secrets.RPC_URL_99 }}

  pricers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Run pricers tests
        run: pnpm test:pricers
        env:
          RPC_URL_1: ${{ secrets.RPC_URL_1 }}

  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Run liquidation execution tests
        run: pnpm test:bot
        env:
          RPC_URL_1: ${{ secrets.RPC_URL_1 }}
